title: "Esraa Ahmed AboAli | Finance, Analytics & Operational Excellence – Transforming Data into Strategic Results"
description: "Strategic finance and operations professional with global experience in analytics, business development, and risk management. I deliver data-driven insights and process optimization that drive measurable business impact across markets."

remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-include-cache

author:
  name: "Esraa Ahmed AboAli"
bio: "Strategy & Business Transformation\nFrom data to decisions. Driving measurable impact"  location: "Cairo, Egypt"
minimal_mistakes_skin: "default"  # can change later to "air", "contrast", "dark"

search: true
